/*
 * eventcodes.c
 *
 * Created: 09.11.2011 г. 16:46:30
 *  Author: mmirev
 */ 

#include "eventcodes.h"


/* main.c */
DEFINE_EVENT_CODE( ADC_HANDLER )
DEFINE_EVENT_CODE( TURN_LAMP_ON_WITH_DELAY_HANDLER )
DEFINE_EVENT_CODE( TURN_LAMP_OFF_WITH_DELAY_HANDLER )
DEFINE_EVENT_CODE( SAVE_BRIGHTNESS_VALUE_HANDLER )
DEFINE_EVENT_CODE( SECONDS_TIMER_HANDLER )
DEFINE_EVENT_CODE( RESET_MANUAL_STATE )

/* encoder.h */
DEFINE_EVENT_CODE( READ_ENCODER_HANDLER )
DEFINE_EVENT_CODE( READ_BUTTON_HANDLER )

DEFINE_EVENT_CODE( BUTTON1_PRESS )
DEFINE_EVENT_CODE( BUTTON2_PRESS )
DEFINE_EVENT_CODE( ENCODER_STATUS_CHANGE )

/* brightness.h */
DEFINE_EVENT_CODE( BRIGHTNESS_CHANGE )
DEFINE_EVENT_CODE( PROCESS_QUEUE_HANDLER )

/* adc.h */
DEFINE_EVENT_CODE( ADC_RUN_HANDLER )
DEFINE_EVENT_CODE( COMPARATOR_FINISH )
DEFINE_EVENT_CODE( TOUCH_PIN_HANDLER )
DEFINE_EVENT_CODE( PIN_TOUCH )

/* indicator.h */
DEFINE_EVENT_CODE( PWM_INDICATOR_HANDLER )
DEFINE_EVENT_CODE( BLINK_HANDLER )
